name: Build Windows Executable with PyInstaller

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # If you have a requirements.txt file:
          # pip install -r requirements.txt

      - name: Package Application with PyInstaller
        run: |
          # Replace 'your_script.py' with your main Python script or 'your_app.spec' if using a spec file
          pyinstaller -F --collect-all apprise --collect-all bs4 CheckRoyalCaribbeanPrice.py
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Executable
          path: dist/CheckRoyalCaribbeanPrice.exe # Adjust 'your_script.exe' to match your output filename
